blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/matthewbrooker/workout-timer/discussions
    about: Ask questions and discuss ideas with the community
  - name: Discord Community
    url: https://discord.gg/workout-timer
    about: Join our Discord server for real-time chat
  - name: Documentation
    url: https://workout-timer.dev
    about: Check our documentation for guides and API reference
  - name: Security Issues
    url: https://github.com/matthewbrooker/workout-timer/security/policy
    about: Please report security vulnerabilities via email (see SECURITY.md)