name: Feature Request
description: Suggest an idea or enhancement for this project
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your feature request! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when I can't save my custom workout configurations...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: |
        Add a localStorage integration that allows saving and loading timer configurations.
        The API could look like:
        - timer.saveConfig(name: string)
        - timer.loadConfig(name: string)
        - timer.listConfigs()
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: |
        I've considered:
        - Manually storing configs in my app's state
        - Using a third-party state management library
        - Creating a wrapper component

  - type: textarea
    id: api
    attributes:
      label: API Design
      description: If applicable, show how you envision using this feature
      render: tsx
      placeholder: |
        const timer = useTimer({
          type: 'custom',
          persist: true,
          persistKey: 'my-workout'
        });
        
        // Or
        const savedConfigs = useTimerConfigs();
        const timer = useTimer(savedConfigs.get('morning-routine'));

  - type: dropdown
    id: package
    attributes:
      label: Target Package
      description: Which package should this feature be added to?
      options:
        - "@workout-timer/core"
        - "@workout-timer/react"
        - "@workout-timer/react-ui"
        - "New package"
        - "Not sure"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Critical - Blocking my use case"
        - "High - Would significantly improve my workflow"
        - "Medium - Nice to have"
        - "Low - Future consideration"
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      options:
        - label: I am willing to submit a PR for this feature
        - label: I would like guidance on implementing this
        - label: I can help test this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: I have clearly described the problem and solution
          required: true
        - label: I have considered alternatives
          required: true